config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :services
  resources :salons
  root to: 'salons#index'

  namespace :api do
    namespace :v1 do
    	resources :salons do
	    	collection do
	        post 'get_time_slot_for_service'
	        post 'service_booking'
	      end
	    end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/salon.rb
class Salon < ApplicationRecord
	has_many :services, dependent: :destroy
	has_many :bookings, dependent: :destroy
	validates :company_name, :gstin, :pan_number, :address, :no_of_chairs, presence: true
	validates :no_of_chairs, numericality: { only_integer: true }
end

app/controllers/api/v1/salons_controller.rb
class Api::V1::SalonsController < ApplicationController
	def get_time_slot_for_service
		errors = []
    data = []
		salon = Salon.find_by(id: params[:salon_id])
		service = salon.services.find_by(id: params[:service_id])
		if salon.present? && service.present?
      data = SalonSerializer.new(service, root: false) 
    else
      errors << 'Salon / service is not present'
    end
		render(
      json: {
        success: true,
        data: data,
        errors: errors
      },
      status: 201
    )
	end

  def service_booking
    service_book = Booking.new(booking_params)

    if service_book.save
      render(
        json: { 
          success: true,
          data: JSON.parse(service_book.to_json),
          errors: []
        },
        status: 201
      )
    else
      api_error(status: 500, errors: service_book.errors.full_messages)
    end
  end

  def booking_params
    array = [
    	:full_name,
    	:phone_no,
      :salon_id,
      :service_id,
      :booking_time
    ]

    JSON.parse(params.to_json).symbolize_keys.slice(*array)
  end
end

app/controllers/salons_controller.rb
class SalonsController < ApplicationController
  before_action :set_salon, only: %i[ show edit update destroy ]

  # GET /salons or /salons.json
  def index
    @salons = Salon.all
  end

  # GET /salons/1 or /salons/1.json
  def show
  end

  # GET /salons/new
  def new
    @salon = Salon.new
  end

  # GET /salons/1/edit
  def edit
  end

  # POST /salons or /salons.json
  def create
    @salon = Salon.new(salon_params)

    respond_to do |format|
      if @salon.save
        format.html { redirect_to salon_url(@salon), notice: "Salon was successfully created." }
        format.json { render :show, status: :created, location: @salon }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @salon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salons/1 or /salons/1.json
  def update
    respond_to do |format|
      if @salon.update(salon_params)
        format.html { redirect_to salon_url(@salon), notice: "Salon was successfully updated." }
        format.json { render :show, status: :ok, location: @salon }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @salon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salons/1 or /salons/1.json
  def destroy
    @salon.destroy

    respond_to do |format|
      format.html { redirect_to salons_url, notice: "Salon was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salon
      @salon = Salon.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def salon_params
      params.require(:salon).permit(
        :company_name,
        :gstin,
        :pan_number,
        :address,
        :no_of_chairs
      )
    end
end

app/helpers/salons_helper.rb
module SalonsHelper
end

app/views/salons/_form.html.erb
<%= form_with(model: salon, local: true) do |form| %>
  <% if salon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(salon.errors.count, "error") %> prohibited this salon from being saved:</h2>

      <ul>
      <% salon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>Comapny Name: <%= form.text_field :company_name%></div>
  <div>GSTIN: <%= form.text_field :gstin %></div>
  <div>Pan Number: <%= form.text_field :pan_number %></div>
  <div>Address: <%= form.text_area :address %></div>
  <div>No. of Chairs: <%= form.text_field :no_of_chairs %></div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/salons/edit.html.erb
<h1>Editing Salon</h1>

<%= render 'form', salon: @salon %>

<%= link_to 'Show', @salon %> |
<%= link_to 'Back', salons_path %>

app/views/salons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Salons</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salons.each do |salon| %>
      <tr>
        <td><%= link_to 'Show', salon %></td>
        <td><%= link_to 'Edit', edit_salon_path(salon) %></td>
        <td><%= link_to 'Destroy', salon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Salon', new_salon_path %>

app/views/salons/new.html.erb
<h1>New Salon</h1>

<%= render 'form', salon: @salon %>

<%= link_to 'Back', salons_path %>

app/views/salons/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_salon_path(@salon) %> |
<%= link_to 'Back', salons_path %>